# Generated by Django 3.0.6 on 2020-06-03 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bantuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100, unique=True)),
                ('Tahun', models.CharField(max_length=4)),
                ('Sumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100, unique=True)),
                ('Kode', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100, unique=True)),
                ('Kode', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keluarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomerKK', models.CharField(max_length=20, unique=True)),
                ('Alamat', models.CharField(max_length=255)),
                ('Desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Desa')),
            ],
        ),
        migrations.CreateModel(
            name='Rt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PenerimaBantuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bantuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Bantuan')),
                ('Keluarga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Keluarga')),
            ],
        ),
        migrations.CreateModel(
            name='Penduduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100)),
                ('TmpLahir', models.CharField(max_length=100)),
                ('TglLahir', models.DateField()),
                ('Alamat', models.CharField(max_length=255)),
                ('Desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Desa')),
                ('Rt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Rt')),
                ('Rw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Rw')),
            ],
        ),
        migrations.AddField(
            model_name='keluarga',
            name='Rt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Rt'),
        ),
        migrations.AddField(
            model_name='keluarga',
            name='Rw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Rw'),
        ),
        migrations.AddField(
            model_name='desa',
            name='Kecamatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Kecamatan'),
        ),
    ]
