# Generated by Django 3.0.6 on 2020-06-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desa',
            name='Kode',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
