# Generated by Django 3.0.6 on 2020-06-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20200603_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keluarga',
            name='Rt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keluarga',
            name='Rw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='Rt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='Rw',
            field=models.IntegerField(default=0),
        ),
    ]
