# Generated by Django 3.0.6 on 2020-06-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_auto_20200604_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desa',
            name='Nama',
            field=models.CharField(max_length=100),
        ),
    ]
