# Generated by Django 3.0.6 on 2020-06-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_auto_20200604_1047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Penduduk',
            new_name='Warga',
        ),
    ]
