# Generated by Django 3.0.6 on 2020-06-14 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0008_auto_20200604_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('Desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Desa')),
            ],
        ),
    ]
