# Generated by Django 3.0.7 on 2020-06-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0009_userdesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='warga',
            name='NikValid',
            field=models.BooleanField(default=False),
        ),
    ]
