# Generated by Django 3.0.7 on 2020-06-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0010_warga_nikvalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NikChanged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReplacedNik', models.CharField(default='', max_length=17, unique=True)),
                ('ReplacedDate', models.DateField()),
                ('Warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Warga')),
            ],
        ),
    ]
