# Generated by Django 3.0.7 on 2020-07-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0011_nikchanged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keluarga',
            options={'ordering': ('NomerKK',)},
        ),
        migrations.AlterField(
            model_name='keluarga',
            name='NomerKK',
            field=models.CharField(db_index=True, max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='warga',
            name='Nik',
            field=models.CharField(db_index=True, default='', max_length=17, unique=True),
        ),
    ]
