# Generated by Django 3.0.8 on 2020-07-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0013_auto_20200715_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='penerimabantuan',
            name='Status',
            field=models.CharField(choices=[('0', 'Usulan'), ('1', 'Disetujui')], default='1', max_length=1),
        ),
    ]
