# Generated by Django 3.0.8 on 2020-07-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0014_penerimabantuan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='penerimabantuan',
            name='TglPengajuan',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
