# Generated by Django 3.0.8 on 2020-12-16 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0015_penerimabantuan_tglpengajuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penerimabantuan',
            name='Status',
            field=models.CharField(choices=[('0', 'Usulan'), ('1', 'Disetujui')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='StatusNonAktif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('0', 'Residu'), ('1', 'Double Data'), ('2', 'Belum Perekaman'), ('3', 'Meninggal')], default='0', max_length=1)),
                ('UpdateDate', models.DateField(default='2020-01-01')),
                ('Warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Warga')),
            ],
        ),
    ]
