# Generated by Django 3.2.4 on 2021-07-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0016_auto_20201216_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usulan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomerKK', models.CharField(db_index=True, max_length=17, unique=True)),
                ('Nik', models.CharField(max_length=17)),
                ('Nama', models.CharField(max_length=100)),
                ('Alamat', models.CharField(max_length=255)),
                ('Rt', models.IntegerField(default=0)),
                ('Rw', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
            ],
        ),
    ]
