# Generated by Django 3.2.4 on 2021-07-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0017_usulan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usulan',
            name='NomerKK',
            field=models.CharField(db_index=True, default='', max_length=17, unique=True),
        ),
    ]
