# Generated by Django 3.2.4 on 2021-07-15 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0018_alter_usulan_nomerkk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usulan',
            name='Nik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.warga'),
        ),
    ]
