# Generated by Django 3.2.4 on 2021-07-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0021_auto_20210715_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usulan',
            name='Nik',
        ),
        migrations.RemoveField(
            model_name='usulan',
            name='NomerKK',
        ),
        migrations.AddField(
            model_name='usulan',
            name='Keluarga',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Database.keluarga'),
        ),
        migrations.AddField(
            model_name='usulan',
            name='Warga',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Database.warga'),
        ),
    ]
