# Generated by Django 2.2.10 on 2021-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0024_auto_20210720_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='Status',
            field=models.CharField(choices=[('Usulan', 'Usulan'), ('Disetujui', 'Disetujui')], default='Usulan', max_length=10),
        ),
    ]
