# Generated by Django 2.2.10 on 2021-07-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0025_auto_20210720_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='Status',
            field=models.CharField(choices=[('0', 'Usulan'), ('1', 'Disetujui')], default='0', max_length=1),
        ),
    ]
