# Generated by Django 2.2.10 on 2021-07-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0028_auto_20210720_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='Status',
            field=models.CharField(choices=[('0', 'Usulan'), ('1', 'Disetujui')], default='usulan', max_length=10),
        ),
    ]
