# Generated by Django 2.2.10 on 2021-07-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0029_auto_20210720_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='Status',
            field=models.CharField(choices=[('usulan', 'Usulan'), ('disetujui', 'Disetujui')], default='usulan', max_length=10),
        ),
    ]
